language: node_js
node_js:
- lts/*
script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: KaKb1+xfUEW+MdNlFAsFdObuy3dd8yvkvxsR0tiObwjow+IWRfn4FHT6nXtNL6Egc3JJqci3Kt8CBp4spM1l+ypsdJOI3eBu9m5EWRtrXSMB7RORO4r2GG3jmIIDtB/7S5hy4RORbXODmEsQCXy2NNrjyza7D2XITqL03lJPM8BNgo/+EzJ6I9W742ES2ulARm4iQ9HeqT0VysJqhxo9HR4Ssx5U7LZVJtbdydks1RDrp6jIAHRneL5BZltUB4YYzsAenPk0W6SWCHRclKK5uaRnps58FdbqxISpWfpEOfDyVamqnudzQvXDRgFyb7fjBGL+pXeFUqMvuXGs3V+r2z9zu+5p7txlTsmuI7Z62D4Pp7qIh2Rv7qrNfLg33PQNNXiNKqaHZtgOisjlMGwnAGPTcOSdj1zC/l8CGWd0yVlIs2jgOEqn1W0oyHvlI+J+AR08ZOsQ+6mLXB6cgH1msLwXJua6ATfitEA4tPxHKotfo8s4F54sGMFxgqEBPn00NBEmgf2WRMrd5jUPgeVPVCtpTswM2NxKikY35LMCg8gsnZzihklyc7FYCSNh/CBJ8PgTBw788m8sXSEyg+RhrZm8ox1dpuEnyR7e4kE0xunj20XB+CjslG/AjYIdaBvHY5AB2cE6Db0DKAgy9akWgT0eCqwA1Xtyxi0D2O1xGus=
