language: node_js
node_js:
- lts/*
script:
- npm run build
deploy:
  provider: firebase
  token:
    secure: jPi6Wf9ukozSwO8nu2cYx6OlmET0/1141l2SbwH26p9cp7uIxVIJjQkhcSMuA5BzWjmIpc4wtVYQrgdoFGaYHlb9O70B8O0cGHvYbmRmnKy6I079Z9G8+K11uuScS6rO/SUOThW0QawsZUbofCWb0IHrYsGdHegKthR7NnVG+Ws8oarm6Y8E6/A41buxMchXHdZMTeCtlykUgq0wMBWN03R114kKTC+2Lq5cQ55tUIwG1H0BkifWq2jt+LC84sRLrYaHCULMyow5q0VFGYnTHlEhSEdne4PDXq1Z00U8GBCQ2PvA6GBdH4AXV8z3hC9qx6rn6UIMCtK7kf/YNkkVbLsLuDgc0JPFksPBPlDD6VJRVcndJ0FFl8hEwWmGDyp5E4BMQa0E8qZdwrGA5UibKbLPZFKppEsyzumpeqXqRLPeWEpGX1xUMxTfBiyey8Z1TBYbb2nr2SAbjaFpmmzxEJXF45f8pyydRFExELzN9iy7SgUOBIyOzVdfmR7apJOc9aEaTOOtE586kE5SgaxYnqBCR56ShXsce/0PDa4aXUc6pRMcwX5925DZ0uhEMLMq0oCRRHhbbwtWvAG4QGIMTlE1zLP02YtQ5XReQhPumPmS3k8j0L04UN1sVxVVuoca2lPL7AVO2tsyr0b790hMgJt8IADf+H1rzdA2kJ7OZfA=
  skip_cleanup: true
